"""Generate the per-tool README sections from the live --help epilogs.

Single source: each shipped tool's worked example lives in its `--help`
epilog (gate G0.9 pins that epilog to the tool's literal output), and the
README section for the tool is rendered from the same epilog here, so the
README can never drift from the CLI.

Usage:

    python -m qreals.readme [README.md]

rewrites the block between the TOOL-SECTIONS markers in place. The test
suite renders the sections and asserts the committed README matches.
"""

from __future__ import annotations

import sys
from pathlib import Path

BEGIN = "<!-- TOOL-SECTIONS:BEGIN (generated by python -m qreals.readme) -->"
END = "<!-- TOOL-SECTIONS:END -->"

# (subcommand, epilog builder name) for every shipped tool with a worked
# example. Order is the order the sections appear in the README.
_TOOLS = ("denom", "bricks", "conj", "collapse", "check")


def _sections() -> str:
    from . import app as app_mod

    parser = app_mod._build_parser()
    helps = {
        action.dest: {c.prog.split()[-1]: c for c in action.choices.values()}
        for action in parser._actions
        if hasattr(action, "choices") and action.choices
    }
    subparsers = helps["command"]
    parts: list[str] = []
    for tool in _TOOLS:
        sub = subparsers[tool]
        epilog = getattr(app_mod, f"_{tool}_help_epilog")()
        one_liner = _one_liner(parser, tool)
        parts.append(f"### `qreals {tool}`\n")
        parts.append(one_liner + "\n")
        parts.append("```text\n" + epilog.rstrip("\n") + "\n```\n")
    return "\n".join(parts).rstrip("\n") + "\n"


def _one_liner(parser, tool: str) -> str:
    for action in parser._actions:
        if hasattr(action, "_choices_actions"):
            for choice in action._choices_actions:
                if choice.dest == tool:
                    text = " ".join(choice.help.split())
                    return text[0].upper() + text[1:] + "."
    raise KeyError(tool)


def render_block() -> str:
    return BEGIN + "\n\n" + _sections() + "\n" + END


def update_readme(path: Path) -> bool:
    """Rewrite the marker block; returns True when the file changed."""
    text = path.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise ValueError(f"{path} is missing the TOOL-SECTIONS markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + render_block() + tail
    if updated != text:
        path.write_text(updated, encoding="utf-8")
        return True
    return False


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    path = Path(args[0]) if args else Path("README.md")
    changed = update_readme(path)
    print(f"{path}: {'updated' if changed else 'already in sync'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
